### ISSUE TITLE
Azure DevOps Self-hosted VMSS not working using correct Version of Microsoft.Azure.DevOps.Pipelines.Agent extension with Ubuntu 24.04

### ISSUE THREAD

**Issue by markDmullins** [microsoft/vsts-azurevm-extension#236] opened 2024-07-29 11:45 UTC
When deploying the Ubuntu 24.04 image within an Azure virtual machine scale set for a VMSS pool of Azure DevOps, the [Microsoft.Azure.DevOps.Pipelines.Agent](https://github.com/microsoft/vsts-azurevm-extension) extension is added, using version 1.2.3 instead of the current latest version 1.2.5.2

1.2.3 of the script has a known issue with Ubuntu24.04 https://github.com/actions/runner-images/issues/10122

Although a recent commit https://github.com/microsoft/vsts-azurevm-extension/pull/235 has fixed the issue Azure DevOps is still using version 1.23 

When will this new version be used by Azure DevOps and the underlying issue resolved

**Comment by DevOpsAzurance** [comment] 2024-07-29 15:48
Same here...

Still having this issue, building both off the latest release and main. This is my VMSS Extension version per 'az vmss extension list':

{
"autoUpgradeMinorVersion": false,
"enableAutomaticUpgrade": null,
"forceUpdateTag": null,
"id": null,
"name": "Microsoft.Azure.DevOps.Pipelines.Agent",
"protectedSettings": null,
"protectedSettingsFromKeyVault": null,
"provisionAfterExtensions": null,
"provisioningState": null,
"publisher": "Microsoft.VisualStudio.Services",
"settings": {
"agentDownloadUrl": "https://vstsagentpackage.azureedge.net/agent/3.241.0/vsts-agent-linux-x64-3.241.0.tar.gz",
"agentFolder": "/agent",
"enableScriptDownloadUrl": "https://vstsagenttools.blob.core.windows.net/tools/ElasticPools/Linux/15/enableagent.sh",
"isPipelinesAgent": true
},
"suppressFailures": null,
"type": null,
"typeHandlerVersion": "1.23",
"typePropertiesType": "TeamServicesAgentLinux"
}

...

Since this extension does not support automatic upgrades, if I need to upgrade, how would I go about doing this without having to rebuild the VMSS resource? I am getting this when running 'az vmss extension upgrade -g MyResourceGroup -n MyScaleSet':

(OperationNotAllowed) Operation 'VirtualMachineScaleSets.ExtensionRollingUpgrade.POST' is not allowed on Virtual Machine
Scale Set 'MyScaleSet'.
Code: OperationNotAllowed
Message: Operation 'VirtualMachineScaleSets.ExtensionRollingUpgrade.POST' is not allowed on Virtual Machine Scale Set 'E
MyScaleSet'.

I assume this will get pushed via any updates on the ADO side.

I rerun the image build on the 14th and 28th of each month and this is causing my team to have to delete the latest version of in our compute gallery every time it runs to ensure it continues using the older version.

**Comment by Jason-Clark-FG** [comment] 2024-08-09 13:39
We too have been experiencing this issue. We want to update our Self-Hosted Agent which is based on Ubuntu 20.04 before it becomes EOL. We tried 22.04, but it had issues with the updated version of openssl for a long time. There was a work-around to install openssl 1.x series, but that made us feel less confident in using it. So when 24.04 dropped we decided to try using it. We discovered the same issue as the other responses above. There's always something isn't there!

Anyway, I think we found a work-around for this one as well. Hopefully the fixed version gets added to Azure soon, but in the meantime this will get it working. It involves creating a "shim" `imp` module. With some help from AI and much trial and error I was able to create one and get it to work.

Here's the shim `imp.py`:

```python
# imp.py

import importlib.util
import sys
import types

# Constants
PY_SOURCE = 1
PY_COMPILED = 2
C_EXTENSION = 3
PY_RESOURCE = 4
PKG_DIRECTORY = 5
C_BUILTIN = 6
PY_FROZEN = 7
SEARCH_ERROR = 8

def find_module(name, path=None):
    """Simulate imp.find_module"""
    try:
        spec = importlib.util.find_spec(name, path)
        if spec is None:
            return None
        return (None, spec.origin, ('', '', spec.loader))
    except ImportError:
        return None

def load_module(name, file=None, pathname=None, description=None):
    """Simulate imp.load_module"""
    if name in sys.modules:
        return sys.modules[name]

    spec = importlib.util.spec_from_file_location(name, pathname)
    if spec is None:
        raise ImportError(f"Cannot load module {name}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module

def new_module(name):
    """Simulate imp.new_module"""
    return types.ModuleType(name)

def reload(module):
    """Simulate imp.reload"""
    return importlib.reload(module)

def load_source(name, pathname, file=None):
    """Simulate imp.load_source"""
    if name in sys.modules:
        return sys.modules[name]

    # Load the module from the source file
    spec = importlib.util.spec_from_file_location(name, pathname)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load source module {name} from {pathname}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module

```

We are incorporating it into our VM image and placing it in `/usr/lib/python3.12/imp.py`

Technically I think we only need the `load_source` function as it is used by the `WAAgentUtil.py` module.

Finally, by building this into our image used by our VMSS based Azure DevOps Pipeline Self-Hosted Agent it is working!

Here is the bash script we are using in `packer` to install this "module":

```shell
#!/bin/bash
set -Eeuxo pipefail

printf '%s\n' "Creating a fake imp python module ... "

# Create module
sudo tee /usr/lib/python3.12/imp.py <<'EOF' > /dev/null
# imp.py

import importlib.util
import sys
import types

# Constants
PY_SOURCE = 1
PY_COMPILED = 2
C_EXTENSION = 3
PY_RESOURCE = 4
PKG_DIRECTORY = 5
C_BUILTIN = 6
PY_FROZEN = 7
SEARCH_ERROR = 8

def find_module(name, path=None):
    """Simulate imp.find_module"""
    try:
        spec = importlib.util.find_spec(name, path)
        if spec is None:
            return None
        return (None, spec.origin, ('', '', spec.loader))
    except ImportError:
        return None

def load_module(name, file=None, pathname=None, description=None):
    """Simulate imp.load_module"""
    if name in sys.modules:
        return sys.modules[name]

    spec = importlib.util.spec_from_file_location(name, pathname)
    if spec is None:
        raise ImportError(f"Cannot load module {name}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module

def new_module(name):
    """Simulate imp.new_module"""
    return types.ModuleType(name)

def reload(module):
    """Simulate imp.reload"""
    return importlib.reload(module)

def load_source(name, pathname, file=None):
    """Simulate imp.load_source"""
    if name in sys.modules:
        return sys.modules[name]

    # Load the module from the source file
    spec = importlib.util.spec_from_file_location(name, pathname)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load source module {name} from {pathname}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module

EOF
sudo chmod -v 644 /usr/lib/python3.12/imp.py

```

I think we would need to build a new image without this shim module after the extension package gets updated in Azure, so we will need to keep an eye on that...

Hopefully this is useful to someone else!

Related issues: #233

**Comment by ThibaultLesuisse** [comment] 2024-09-03 09:57
@Jason-Clark-FG Works like a charm! Thank you very much.

**Comment by jbcutting** [comment] 2024-10-02 04:42
Still seeing this a couple months after it was first reported. Hopefully the fix can be properly rolled out soon.

**Comment by jbcutting** [comment] 2024-10-07 17:45
@tkasparek Are you able to facilitate getting the newer version deployed?

**Comment by thordurornmm** [comment] 2024-10-19 20:17
Running in to this a well, deploying an ubuntu 24.04  not working with 1.2.3 or 1.2.5.2

**Comment by tkasparek** [comment] 2024-10-24 13:36
Should be fixed with 1.26.2.0 or higher which is currently being rolled out.

**Comment by NPetersenDK** [comment] 2024-10-28 13:46
Hi,

I have the same issue with the imp module with a completely new VMSS (Scale Set). When will the roll-out be completed fully?

Thanks.

**Closed** 2024-10-31 14:59 UTC

**Comment by jbcutting** [comment] 2024-10-31 15:03
@tkasparek , I can confirm this is working for me now. Thanks so much!

**Comment by ncook-hxgn** [comment] 2024-11-06 16:49
@VemundH is that something that's being mandated by an errant .terraform.lock.hcl file?

**Comment by VemundH** [comment] 2024-11-06 18:12
Not that know of. I am of the impression that all updates to this extension is pushed from Azure DevOps.

Looks like others are experiencing the same behavior: https://github.com/microsoft/vsts-azurevm-extension/issues/241#issuecomment-2450213761
